### ISSUE TITLE
run multiple command

### ISSUE THREAD

**Issue by jianshu93** [mbhall88/ssubmit#1]
Hello,

I did not see how to run bunch of commands. For example to active conda environment and then run a command et.al.

Thanks,

Jianshu

**Comment by mbhall88** [comment]
You can use [chaining operators](https://www.diskinternals.com/linux-reader/bash-chain-commands/) in the command to do that.

For example, to activate a conda env and then align something using the logical AND operator (`&&`)

```bash
ssubmit map "conda activate minimap2 && minimap2 ref.fa in.fq"
```

you can also use `;` instead of `&&` to run the commands sequentially and independently of each other.

Does that answer your question?

**Comment by jianshu93** [comment]
Yes thanks. 

I will close it.

Jianshu
